---
- name: YOUR_PROJECT server installation
  hosts: YOUR_PROJECT
  remote_user: root
  vars_files:
    - config/host.yml
    - config/utils.yml
    - config/users.yml
    - config/ssh.yml

  pre_tasks:
    - name: Updating cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - utils
    - users
    - ufw
    - docker
    - ssh
...

